FROM quay.io/centos/centos:stream9

RUN dnf -y install dnf-utils; \
    dnf config-manager --set-enabled crb; \
    dnf -y install epel-release epel-next-release; \
    dnf -y install rsync chromium openssh-clients npm python3 python3-libvirt python3-yaml bash
